#!/usr/bin/env bash
# This script kills the "4-to_infinity_and_beyond" process using kill

# shellcheck disable=SC2009
pid=$(ps -ef | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')
if [ -n "$pid" ]; then
  kill "$pid"
fi

